### ISSUE TITLE
Proposal to merge repositories

### ISSUE THREAD

**Issue by cyberalien** [Azumgi/Material-Icons-Complete#1]
I have similar repository with updated icons: https://github.com/cyberalien/google-material-design-icons-updated

Both repositories have something that other repository doesn't, maybe do something like merging them?

Your repository has scripts for building fonts, which is what many people want. However many icons include bugs. Some icons have wrong dimensions, some have paths that ruin their look. Also some icons are missing that existed in version 3.

My repository has fixed icons that had bugs, added icons that existed in version 3 but are missing on material.io (and their variations for all 5 themes) and added few icons people requested. There is also script to generate PNG files that at least one person wanted.

So both repositories have things that are missing in other repository. Maybe somehow merge them?

**Comment by jossef** [comment]
Hey from the author of https://github.com/jossef/material-design-icons-iconfont
Joining the request, I'm in the favor of merging our work

jossef12@gmail.com

**Comment by cyberalien** [comment]
Awesome.

I suggest to create new project, with full access for all of us. Why project instead of repository? Because I suggest to split parts of it into several repositories. For project name I think "material-icons" fits well and its available (grabbed it, will invite if you are ok with it).

Why not fork old repository? Old official repository is a mess. There are too many files that aren't needed by vast majority of users, many duplicates. Also icons structure have changed since version 3 because each icon has 5 themes.

Formats that people want:
- SVG
- Font
- PNG

With 5 themes for each icon and about 1000 icons, total number of icons is about 5k. That's a lot of files for one repository. Because of that I suggest to split icons into at least 2 repositories:

1. SVG + font. Those are most common formats people want.

2. PNG repository. Some people want PNG files. Problem is there are many size/color combinations, so for 5k icons it would be a lot of files. People who need PNG files are unlikely to be able to build files themselves, so simply giving them tools is not enough. Therefore it would be nice to have separate repository with PNG files and tools for building them without polluting main repository.

Additional repositories can be created for other formats, such as iOS imagesets or whatever other format people will request. Those repositories, just like PNG repository, will have build tools that will use main repository as dependency and build files from that.

Next issue is build tools and monitoring of material.io. Icons on material.io have issues. However at some point Google team might fix those issues or update icons. So there should be way to monitor material.io for changes. I'm not sure how to do it, my current script is rather messy, however I think it should be split from main repository.

Tools for building font can be in main repository because both font and SVG are there.

What do you think about this?

**Comment by cyberalien** [comment]
Forgot about two-tone icons.

There are bunch of two-tone icons among new icons. Problem is its not just two-tone theme, they are in all themes. For example, there are plenty of them in "editor" category for baseline theme, like this one: https://github.com/cyberalien/google-material-design-icons-updated/blob/master/svg/editor/baseline-border_color.svg

I don't know much about exporting to fonts, would I be correct in assuming that those icons will have to be fixed to not include opacity?

**Comment by Dreomite** [comment]
Hey @cyberalien, @jossef! I'm all up for using my code and research for something better, but I won't participate directly in it (most likely).
This project is just 2 simple scripts I made 4 months ago to experiment with icons a little and I uploaded it to GitHub only because

1. I kind of promised to do this.
2. I couldn't find similar projects so my project would be a good starting point for those who want to implement font generating in their own project.

It would be nice to participate in repos merging to create something better, but currently, all my free time is taken by several side projects that are very important to me. I definitely like the idea, though!

Despite the fact that I won't directly participate in it (most likely), I still can allocate several hours to answer some questions regarding font generating or maybe discuss some design choices.

---

*RE: Monitoring changes on material.io*

Splitting it to a separate repo is a good idea. The simplest parser + git would do it. Some maintainer has to run it once a month or so so it will redownload all the icons, and if there are any changes, git will notice that.

*RE: Two-tone icons and fonts.*

I think you're right and two-tone icons in other themes have to be manually edited before being used in a font, or you will get mess [like this](https://raw.githubusercontent.com/Azumgi/Material-Icons-Complete/master/media/transparency_representation.jpg). I believe, removing semi-transparent parts and using outlines/tone-inverting would do it. So it would look like this:

![Screenshot (93)](https://user-images.githubusercontent.com/35058624/58009865-ff491080-7af7-11e9-9b5f-8a66aacaccdc.png)


But is this a good solution? The resulting icons won't be something Google created.

I don't think Two-tone themed icons should be converted to the font at all. If do what I proposed, it will basically become Outlined v2 with some icons having no difference. Like `help`/`help_outline` or `hourglass`/`hourglass_full`.

---

It would be cool if you guys combined your efforts to make this project a thing. In this case, I will archive my repo and put a link to your project.

This issue can also be used for coordination if you want it.

**Comment by cyberalien** [comment]
That approach to two-tone icons is a possible solution, but its also tricky:

1. There are icons like this one: https://github.com/cyberalien/google-material-design-icons-updated/blob/master/svg/device/baseline-signal_cellular_connected_no_internet_3_bar.svg

In such icons transparent part is too small to change it to outline.

2. Variations of those icons like this: https://github.com/cyberalien/google-material-design-icons-updated/blob/master/svg/device/round-signal_cellular_connected_no_internet_4_bar.svg

Its rounded. While changing baseline icon would be fine because there is two-tone icon that looks identical to original baseline, rounded icons don't have variations.

I have a different possible solution: split twotone icons into 2 glyphs (one for paths with opacity 1, one for paths with opacity 0.3) and use mix of :before and :after:
```
.material-icons { position: relative; }
.material-icons:after { position: absolute; left: 0; top: 0; right: 0; bottom: 0; opacity: .3; }

.material-icons.signal_cellular_connected_no_internet_4_bar:before { content: '\e540'; }
.material-icons.signal_cellular_connected_no_internet_4_bar:after { content: '\e541'; }
```
So that way 2 glyphs are displayed in place of one. What do you think about this approach?

**Comment by Dreomite** [comment]
Yeah, with this approach some icons do look weird.

![image](https://user-images.githubusercontent.com/35058624/58026054-5d88ea00-7b1e-11e9-88cc-b8202fb2d95c.png)

Unfortunately, I'm not a web dev, so I can't give you my opinion on your solution. It sounds good 😄 My solution was based on assumption there can be only 1 font file for every theme, so desktop users could make use of it. But I don't know anything about who use Materials Icons and what it is used for in general. So how to go around it is totally up to you and @jossef.

**Comment by jossef** [comment]
@cyberalien
> That's a lot of files for one repository

totaly agree, this was the original cause for me to create [mdidx](https://github.com/jossef/material-design-icons-iconfont). as a developer it drove me nuts to clone the original project.

I don't know what will be the best practice and seems to split it to multiple repos sounds ok

- svgs
- iconfont + css (for dev needs i.e. `npm install`)
- pngs
- build scripts

---

@cyberalien
> build tools and monitoring of material.io

Created a build script to scrape-out the new stuff Google is adding to the compiled font. downloaded with user-agent tricks straight from their CDN (Google Fonts)

https://github.com/jossef/material-design-icons-iconfont/blob/master/build/build.js

---

@cyberalien
> about two-tone icons

fonts does not support more than one color. we can work this around by layering 2 characters with different colors overlay one another or embed the svg (can be done in css)


---

@Azumgi
> Some maintainer has to run it once a month or so so it will redownload all the icons

fully/partially automating this and host this somewhere to run periodically


---

In general, Google's designers doing good job. I'm in the favor of sticking to the "original spec" as possible and accessing their awesome work. there are many projects that add custom Icons such as https://materialdesignicons.com/ and they are a mess IMHO

I have small amount of time during weekends. let's schedule a kick-off chat privately 
jossef12@gmail.com

**Comment by cyberalien** [comment]
Yes, I agree about "original spec". In next few days I'll try to test how to implement two-tone icons in font by layering 2 characters. I hope it will work 🙏

**Comment by cyberalien** [comment]
It seems to work: https://cyberalien.github.io/font-test/tests/sample1.html

One font, using :before pseudo-element with .3 opacity for semi-transparent part of icon, using :after pseudo-element with 1 opacity for normal part of icon.

**Comment by cyberalien** [comment]
In addition to previous post, I've tried making ligatures work, so font could use same syntax as old font, but it is impossible.

So looks like code like this won't work:
```
<i class="material-icons">battery_charging_full</I>
```
I tried mixing ligatures as different layers (such as "battery_charging" as first part, "_full" as second part), but then its impossible to target one part of ligature to position it near first part. :first-letter targets actual first letter, not ligature.

So I think it will have to be done like in other glyph fonts (and in sample I've posted above): big css file will have to be included and icon name passed as attribute or class name:
```
<i class="material-icons material-icons-battery_charging_full"></I>
```
or
```
<i class="material-icons" data-icon="battery_charging_full"></I>
```

**Comment by jossef** [comment]
> In addition to previous post, I've tried making ligatures work, so font could use same syntax as old font, but it is impossible.
> 
> So looks like code like this won't work:
> 
> ```
> <i class="material-icons">battery_charging_full</I>
> ```
> 
> I tried mixing ligatures as different layers (such as "battery_charging" as first part, "_full" as second part), but then its impossible to target one part of ligature to position it near first part. :first-letter targets actual first letter, not ligature.
> 
> So I think it will have to be done like in other glyph fonts (and in sample I've posted above): big css file will have to be included and icon name passed as attribute or class name:
> 
> ```
> <i class="material-icons material-icons-battery_charging_full"></I>
> ```
> 
> or
> 
> ```
> <i class="material-icons" data-icon="battery_charging_full"></I>
> ```

@cyberalien 

it's possible, google used in their compiled font only the first letter of the ligature as the key and the rest is the mapping

e.g.

```
    "4k_plus": "E969",
    "4k": "E072",
```

`4` -> 
```
k_plus
k
```

**Comment by cyberalien** [comment]
Problem with that is there is a very limited number of first letters.

For example: singular_cellular_1_bar, signal_cellular_connected_no_internet_0_bar, signal_wifi_1_bar_lock have completely different layers, but all of them same first letter "s". So splitting "s" and the rest of ligature would conflict because there can be only one letter "s" in font.

**Comment by cyberalien** [comment]
Closing this because discussion was moved to https://github.com/material-icons/build/issues

@Azumgi you've posted that you most likely won't be participating, but if you change your mind, you are always welcome to join us.
